name: ChatManager
version: '${project.version}'
main: org.stevecv.chatmanager.ChatManager
api-version: '1.20'
depend: [Vault, PlaceholderAPI]
commands:
  discordmarkdownchatmanager:
    description: Allows you to access commands relating to the chat manager
    usage: /<command>
    aliases: [dmcm, discordmarkdowncm, dmchatmanager]
    permission: discordmarkdownchatmanager.admin